'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Search, Eye, PenLine, MoreHorizontal, ArrowRight } from 'lucide-react';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue, } from '@/components/ui/select';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger, } from '@/components/ui/dropdown-menu';
import { StatusBadge } from '@/components/shared/StatusBadge';
import { PROCESOS, ETIQUETAS_REQUERIMIENTO } from '@/lib/mock-data';
const NEXT_STEP = {
    notificacion: { label: 'Ir a Inspección', href: (id) => `/procesos/${id}/inspeccion` },
    inspeccion: { label: 'Ir a Verificación', href: (id) => `/procesos/${id}/verificacion` },
};
export function ProcesosList() {
    const [search, setSearch] = useState('');
    const [filterEstado, setFilterEstado] = useState('todos');
    const filtered = PROCESOS.filter((p) => {
        const matchSearch = p.empresa.nombre.toLowerCase().includes(search.toLowerCase()) ||
            p.inspector.nombre.toLowerCase().includes(search.toLowerCase());
        const matchEstado = filterEstado === 'todos' || p.estado === filterEstado;
        return matchSearch && matchEstado;
    });
    return (_jsxs(Card, { className: "border-border/60 shadow-sm", children: [_jsxs(CardHeader, { className: "flex-row flex-wrap items-center gap-3 pb-3", children: [_jsxs("div", { className: "relative flex-1 min-w-48", children: [_jsx(Search, { className: "absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" }), _jsx(Input, { placeholder: "Buscar empresa o inspector...", value: search, onChange: (e) => setSearch(e.target.value), className: "pl-8 h-9 text-sm" })] }), _jsxs(Select, { value: filterEstado, onValueChange: setFilterEstado, children: [_jsx(SelectTrigger, { className: "h-9 w-44 text-sm", children: _jsx(SelectValue, {}) }), _jsxs(SelectContent, { children: [_jsx(SelectItem, { value: "todos", children: "Todos los estados" }), _jsx(SelectItem, { value: "notificacion", children: "Notificaci\u00F3n" }), _jsx(SelectItem, { value: "inspeccion", children: "Inspecci\u00F3n" }), _jsx(SelectItem, { value: "verificacion", children: "Verificaci\u00F3n" }), _jsx(SelectItem, { value: "cumple", children: "Cumple" }), _jsx(SelectItem, { value: "no_cumple", children: "No cumple" })] })] }), _jsxs("span", { className: "text-xs text-muted-foreground ml-auto", children: [filtered.length, " resultado", filtered.length !== 1 ? 's' : ''] })] }), _jsxs(CardContent, { className: "p-0", children: [_jsxs("div", { className: "grid grid-cols-[2fr_1fr_1fr_1fr_1fr_auto] items-center gap-4 border-b border-border/70 bg-muted/30 px-4 py-2.5", children: [_jsx("span", { className: "text-xs font-semibold uppercase tracking-wide text-muted-foreground", children: "Empresa" }), _jsx("span", { className: "text-xs font-semibold uppercase tracking-wide text-muted-foreground", children: "Proceso" }), _jsx("span", { className: "text-xs font-semibold uppercase tracking-wide text-muted-foreground", children: "Estado" }), _jsx("span", { className: "text-xs font-semibold uppercase tracking-wide text-muted-foreground hidden lg:block", children: "Fecha" }), _jsx("span", { className: "text-xs font-semibold uppercase tracking-wide text-muted-foreground hidden sm:block", children: "Inspector" }), _jsx("span", { className: "text-xs font-semibold uppercase tracking-wide text-muted-foreground", children: "Acciones" })] }), _jsx("div", { className: "divide-y divide-border/50", children: filtered.length === 0 ? (_jsx("div", { className: "py-12 text-center text-sm text-muted-foreground", children: "No se encontraron procesos con los filtros aplicados." })) : (filtered.map((proceso) => {
                            const nextStep = NEXT_STEP[proceso.estado];
                            return (_jsxs("div", { className: "grid grid-cols-[2fr_1fr_1fr_1fr_1fr_auto] items-center gap-4 px-4 py-3 transition-colors hover:bg-muted/30", children: [_jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "truncate text-sm font-medium text-foreground", children: proceso.empresa.nombre }), _jsx("p", { className: "truncate text-xs text-muted-foreground", children: proceso.empresa.direccion })] }), _jsx("span", { className: "text-xs text-muted-foreground", children: ETIQUETAS_REQUERIMIENTO[proceso.tipoRequerimiento] }), _jsx(StatusBadge, { estado: proceso.estado }), _jsx("span", { className: "hidden text-xs text-muted-foreground lg:block", children: proceso.fechaActualizacion }), _jsx("span", { className: "hidden truncate text-xs text-muted-foreground sm:block", children: proceso.inspector.nombre }), _jsxs("div", { className: "flex items-center gap-1 justify-end", children: [_jsx(Link, { to: `/procesos/${proceso.id}`, children: _jsxs(Button, { variant: "ghost", size: "icon", className: "h-8 w-8", children: [_jsx(Eye, { className: "h-3.5 w-3.5" }), _jsx("span", { className: "sr-only", children: "Ver" })] }) }), nextStep && (_jsx(Link, { to: nextStep.href(proceso.id), children: _jsxs(Button, { variant: "ghost", size: "icon", className: "h-8 w-8 text-primary hover:text-primary", children: [_jsx(ArrowRight, { className: "h-3.5 w-3.5" }), _jsx("span", { className: "sr-only", children: nextStep.label })] }) })), _jsxs(DropdownMenu, { children: [_jsx(DropdownMenuTrigger, { asChild: true, children: _jsxs(Button, { variant: "ghost", size: "icon", className: "h-8 w-8", children: [_jsx(MoreHorizontal, { className: "h-3.5 w-3.5" }), _jsx("span", { className: "sr-only", children: "Opciones" })] }) }), _jsxs(DropdownMenuContent, { align: "end", className: "text-sm", children: [_jsx(DropdownMenuItem, { asChild: true, children: _jsxs(Link, { to: `/procesos/${proceso.id}`, className: "flex items-center gap-2", children: [_jsx(Eye, { className: "h-3.5 w-3.5" }), "Ver detalle"] }) }), _jsxs(DropdownMenuItem, { className: "flex items-center gap-2", children: [_jsx(PenLine, { className: "h-3.5 w-3.5" }), "Editar"] })] })] })] })] }, proceso.id));
                        })) })] })] }));
}
