// ─── Catálogos ─────────────────────────────────────────────────────────────
export const INSPECTORES = [
    { id: 'ins-1', nombre: 'Juan Pérez García', idIne: 'PEGA850312HSONRN05' },
    { id: 'ins-2', nombre: 'María López Ruiz', idIne: 'LORM920715MSONPZ08' },
    { id: 'ins-3', nombre: 'Carlos Méndez Torres', idIne: 'METC780430HSONRR03' },
    { id: 'ins-4', nombre: 'Ana García Flores', idIne: 'GAFA950201MSONRN01' },
];
export const EMPRESAS = [
    {
        id: 'emp-1',
        nombre: 'Restaurantes del Sol S.A. de C.V.',
        direccion: 'Av. Pesqueira #140, Col. Centro, Navojoa, Sonora',
        representante: 'Carlos Méndez Ruiz',
        telefono: '642 123 4567',
        giro: 'Restaurante / Alimentos',
        razonSocial: 'Restaurantes del Sol S.A. de C.V.',
    },
    {
        id: 'emp-2',
        nombre: 'Constructora ABC S.A. de C.V.',
        direccion: 'Blvd. Centenario #250, Col. Moderna, Navojoa, Sonora',
        representante: 'Roberto Álvarez Soto',
        telefono: '642 234 5678',
        giro: 'Construcción / Industria',
        razonSocial: 'Constructora ABC S.A. de C.V.',
    },
    {
        id: 'emp-3',
        nombre: 'Alimentos SA de CV',
        direccion: 'Calle Obregón #88, Col. Primer Cuadro, Navojoa, Sonora',
        representante: 'Patricia Estrada Mora',
        telefono: '642 345 6789',
        giro: 'Alimentos / Manufactura',
        razonSocial: 'Alimentos SA de CV',
    },
    {
        id: 'emp-4',
        nombre: 'Logística Express Norte',
        direccion: 'Carr. Navojoa-Álamos km 3, Parque Industrial, Navojoa',
        representante: 'José Ibarra Contreras',
        telefono: '642 456 7890',
        giro: 'Logística / Transporte',
        razonSocial: 'Logística Express Norte S.A. de C.V.',
    },
    {
        id: 'emp-5',
        nombre: 'Fábrica Industrial Sonora',
        direccion: 'Zona Industrial Lote 22, Navojoa, Sonora',
        representante: 'Lucía Morales Vega',
        telefono: '642 567 8901',
        giro: 'Manufactura / Industrial',
        razonSocial: 'Fábrica Industrial Sonora S.A. de C.V.',
    },
    {
        id: 'emp-6',
        nombre: 'Clínica Médica del Valle',
        direccion: 'Calle Guerrero #310, Col. Centro, Navojoa, Sonora',
        representante: 'Dr. Marco Salazar',
        telefono: '642 678 9012',
        giro: 'Salud / Clínica',
        razonSocial: 'Clínica Médica del Valle S.C.',
    },
    {
        id: 'emp-7',
        nombre: 'Taller Automotriz El Pino',
        direccion: 'Av. Aguascalientes #75, Navojoa, Sonora',
        representante: 'Fernando Ríos Espinoza',
        telefono: '642 789 0123',
        giro: 'Taller / Automotriz',
        razonSocial: 'Taller Automotriz El Pino',
    },
    {
        id: 'emp-8',
        nombre: 'Supermercado Familiar González',
        direccion: 'Blvd. Portes Gil #120, Navojoa, Sonora',
        representante: 'Ana González Padilla',
        telefono: '642 890 1234',
        giro: 'Comercio / Supermercado',
        razonSocial: 'Supermercado Familiar González S.A.',
    },
];
// ─── Procesos Mock ──────────────────────────────────────────────────────────
export const PROCESOS = [
    {
        id: 'proc-1',
        empresa: EMPRESAS[0],
        estado: 'inspeccion',
        tipoRequerimiento: 'proteccion_civil',
        inspector: INSPECTORES[0],
        fechaCreacion: '2026-05-21',
        fechaActualizacion: '2026-05-21',
        notificacion: {
            id: 'not-1',
            procesoId: 'proc-1',
            empresaId: 'emp-1',
            tipoRequerimiento: 'proteccion_civil',
            descripcion: 'Se notifica a la empresa sobre la visita de inspección en cumplimiento a los Títulos Sexto y Octavo de la Ley de Protección Civil para el Estado de Sonora.',
            fechaProgramada: '2026-05-23',
            hora: '10:00',
            medioNotificacion: 'Correo electrónico',
            observaciones: 'Se solicita al representante legal esté presente durante la visita de inspección.',
            ordenInspeccionNo: 'INSP-2026-001',
            firmadoPorEmpresa: true,
            firmadoPorInspector: true,
            creadoEn: '2026-05-21T09:00:00Z',
        },
        inspeccion: {
            id: 'insp-1',
            procesoId: 'proc-1',
            empresaId: 'emp-1',
            expediente: 'EXP-2026-001',
            folio: '001',
            fecha: '2026-05-23',
            horaInicio: '10:00',
            horaFin: '11:30',
            inspectorId: 'ins-1',
            acompanante: 'María López Ruiz',
            representanteEmpresa: 'Carlos Méndez Ruiz',
            gradoRiesgo: 'medio',
            observacionesGenerales: 'El establecimiento cuenta con extintores, pero algunos están vencidos. Las lámparas de emergencia funcionan correctamente. Se requiere actualizar el Plan Interno de Protección Civil.',
            diasParaCumplir: 30,
            fechaVerificacion: '2026-06-23',
            horaVerificacion: '10:00',
            evidencias: [],
            secciones: [
                {
                    id: 'sec-pc',
                    titulo: 'II. Protección Civil',
                    items: [
                        {
                            id: 'pc-1',
                            descripcion: 'Cuenta con Unidad Interna de Protección Civil',
                            valor: 'si',
                        },
                        {
                            id: 'pc-2',
                            descripcion: 'Cuenta con Plan Interno',
                            valor: 'no',
                        },
                        {
                            id: 'pc-3',
                            descripcion: 'Manual de Contingencias',
                            valor: 'no',
                        },
                        {
                            id: 'pc-4',
                            descripcion: 'Dictamen Eléctrico',
                            valor: 'si',
                        },
                        {
                            id: 'pc-5',
                            descripcion: 'Dictamen Estructural',
                            valor: 'si',
                        },
                    ],
                },
                {
                    id: 'sec-bomb',
                    titulo: 'III. Bomberos',
                    items: [
                        { id: 'b-1', descripcion: 'Extintores', valor: 'si' },
                        { id: 'b-2', descripcion: 'Lámparas de Emergencia', valor: 'si' },
                        { id: 'b-3', descripcion: 'Detectores de Humo', valor: 'no' },
                        { id: 'b-4', descripcion: 'Señalización de Evacuación', valor: 'si' },
                    ],
                },
            ],
            creadoEn: '2026-05-23T10:00:00Z',
        },
    },
    {
        id: 'proc-2',
        empresa: EMPRESAS[1],
        estado: 'notificacion',
        tipoRequerimiento: 'bomberos',
        inspector: INSPECTORES[1],
        fechaCreacion: '2026-05-20',
        fechaActualizacion: '2026-05-20',
        notificacion: {
            id: 'not-2',
            procesoId: 'proc-2',
            empresaId: 'emp-2',
            tipoRequerimiento: 'bomberos',
            descripcion: 'Se notifica a la empresa para inspección de sistemas contra incendio fijos y semifijos.',
            fechaProgramada: '2026-05-28',
            hora: '09:00',
            medioNotificacion: 'Visita personal',
            observaciones: '',
            ordenInspeccionNo: 'INSP-2026-002',
            firmadoPorEmpresa: true,
            firmadoPorInspector: true,
            creadoEn: '2026-05-20T08:30:00Z',
        },
    },
    {
        id: 'proc-3',
        empresa: EMPRESAS[2],
        estado: 'cumple',
        tipoRequerimiento: 'proteccion_civil',
        inspector: INSPECTORES[0],
        fechaCreacion: '2026-05-10',
        fechaActualizacion: '2026-05-19',
        notificacion: {
            id: 'not-3',
            procesoId: 'proc-3',
            empresaId: 'emp-3',
            tipoRequerimiento: 'proteccion_civil',
            descripcion: 'Inspección de verificación de cumplimiento de medidas de seguridad.',
            fechaProgramada: '2026-05-15',
            hora: '11:00',
            medioNotificacion: 'Correo electrónico',
            observaciones: '',
            ordenInspeccionNo: 'INSP-2026-003',
            firmadoPorEmpresa: true,
            firmadoPorInspector: true,
            creadoEn: '2026-05-10T10:00:00Z',
        },
        verificacion: {
            id: 'ver-3',
            procesoId: 'proc-3',
            empresaId: 'emp-3',
            expediente: 'EXP-2026-003',
            fechaVerificacion: '2026-05-19',
            inspectorId: 'ins-1',
            observacionesGenerales: 'La empresa cumple satisfactoriamente con todos los requerimientos de protección civil. Se verificó que el Plan Interno está actualizado y operativo.',
            resultado: 'cumple',
            fechaProximaRevision: '2027-05-19',
            firmadoPorEmpresa: true,
            firmadoPorInspector: true,
            creadoEn: '2026-05-19T15:00:00Z',
        },
    },
    {
        id: 'proc-4',
        empresa: EMPRESAS[3],
        estado: 'no_cumple',
        tipoRequerimiento: 'bomberos',
        inspector: INSPECTORES[3],
        fechaCreacion: '2026-05-12',
        fechaActualizacion: '2026-05-18',
        verificacion: {
            id: 'ver-4',
            procesoId: 'proc-4',
            empresaId: 'emp-4',
            expediente: 'EXP-2026-004',
            fechaVerificacion: '2026-05-18',
            inspectorId: 'ins-4',
            observacionesGenerales: 'La empresa no cuenta con extintores vigentes ni con detectores de humo en las áreas de almacén. El sistema de evacuación no está debidamente señalizado.',
            resultado: 'no_cumple',
            tipoSancion: 'Apercibimiento',
            fechaLimite: '2026-06-18',
            fechaProximaRevision: '2026-06-18',
            firmadoPorEmpresa: true,
            firmadoPorInspector: true,
            creadoEn: '2026-05-18T14:00:00Z',
        },
    },
    {
        id: 'proc-5',
        empresa: EMPRESAS[4],
        estado: 'cumple',
        tipoRequerimiento: 'proteccion_civil',
        inspector: INSPECTORES[1],
        fechaCreacion: '2026-05-08',
        fechaActualizacion: '2026-05-17',
        verificacion: {
            id: 'ver-5',
            procesoId: 'proc-5',
            empresaId: 'emp-5',
            expediente: 'EXP-2026-005',
            fechaVerificacion: '2026-05-17',
            inspectorId: 'ins-2',
            observacionesGenerales: 'Empresa en cumplimiento. Todos los dictámenes vigentes.',
            resultado: 'cumple',
            fechaProximaRevision: '2027-05-17',
            firmadoPorEmpresa: true,
            firmadoPorInspector: true,
            creadoEn: '2026-05-17T11:00:00Z',
        },
    },
    {
        id: 'proc-6',
        empresa: EMPRESAS[5],
        estado: 'verificacion',
        tipoRequerimiento: 'seguridad',
        inspector: INSPECTORES[2],
        fechaCreacion: '2026-05-14',
        fechaActualizacion: '2026-05-22',
    },
    {
        id: 'proc-7',
        empresa: EMPRESAS[6],
        estado: 'inspeccion',
        tipoRequerimiento: 'bomberos',
        inspector: INSPECTORES[0],
        fechaCreacion: '2026-05-19',
        fechaActualizacion: '2026-05-19',
    },
    {
        id: 'proc-8',
        empresa: EMPRESAS[7],
        estado: 'notificacion',
        tipoRequerimiento: 'sanidad',
        inspector: INSPECTORES[3],
        fechaCreacion: '2026-05-22',
        fechaActualizacion: '2026-05-22',
    },
];
// ─── Stats ──────────────────────────────────────────────────────────────────
export const STATS = {
    totalEmpresas: 120,
    procesosEsteMes: 45,
    cumplen: 68,
    noCumplen: 15,
    enProceso: 37,
    porEstado: [
        { nombre: 'Notificación', valor: 25, porcentaje: 25, color: '#3b82f6' },
        { nombre: 'Inspección', valor: 20, porcentaje: 20, color: '#8b5cf6' },
        { nombre: 'Verificación', valor: 30, porcentaje: 30, color: '#f97316' },
        { nombre: 'Cumplen', valor: 68, porcentaje: 17, color: '#22c55e' },
        { nombre: 'No cumplen', valor: 15, porcentaje: 8, color: '#ef4444' },
    ],
    inspeccionesPorMes: [
        { mes: 'Ene', inspecciones: 28, verificaciones: 22 },
        { mes: 'Feb', inspecciones: 35, verificaciones: 30 },
        { mes: 'Mar', inspecciones: 42, verificaciones: 38 },
        { mes: 'Abr', inspecciones: 38, verificaciones: 35 },
        { mes: 'May', inspecciones: 45, verificaciones: 20 },
    ],
};
// ─── Helpers ────────────────────────────────────────────────────────────────
export const ETIQUETAS_ESTADO = {
    notificacion: 'Notificación',
    inspeccion: 'Inspección',
    verificacion: 'Verificación',
    cumple: 'Cumple',
    no_cumple: 'No cumple',
};
export const ETIQUETAS_REQUERIMIENTO = {
    proteccion_civil: 'Protección Civil',
    bomberos: 'Bomberos',
    seguridad: 'Seguridad',
    sanidad: 'Sanidad',
    ecologia: 'Ecología',
    otro: 'Otro',
};
